FROM node:16.13.1

WORKDIR /app

COPY . .

ARG GHP_ACCESS_TOKEN
ENV GHP_ACCESS_TOKEN=${GHP_ACCESS_TOKEN}
ENV REACT_APP_GRAPHQL_URI=$REACT_APP_GRAPHQL_URI
ENV REACT_APP_SSO_HOST=$REACT_APP_SSO_HOST
ENV REACT_APP_REDIRECT_ON_SIGNOUT_URL=$REACT_APP_REDIRECT_ON_SIGNOUT_URL
ENV REACT_APP_INCLUDE_LOCAL_SCHEMA=$REACT_APP_INCLUDE_LOCAL_SCHEMA

RUN echo “//npm.pkg.github.com/:_authToken=${GHP_ACCESS_TOKEN}” >> .npmrc

RUN yarn run build

COPY entrypoint.sh ./

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8080
